import Head from "next/head";
import Image from "next/image";
import CardHome from "../components/CardHome";
import Footer from "../components/Footer";
import TopNavbar from "../components/Navbar";
import WhatSetApart from "../components/WhatSetApart";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <TopNavbar />
        <WhatSetApart />
        <CardHome />
        <Footer />
      </div>
    </div>
  );
}
